/****************************************************************************
**
** Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
** All rights reserved.
** Contact: Nokia Corporation (qt-info@nokia.com)
**
** This file is part of the Qt3D module of the Qt Toolkit.
**
** $QT_BEGIN_LICENSE:LGPL$
** No Commercial Usage
** This file contains pre-release code and may not be distributed.
** You may use this file in accordance with the terms and conditions
** contained in the Technology Preview License Agreement accompanying
** this package.
**
** GNU Lesser General Public License Usage
** Alternatively, this file may be used under the terms of the GNU Lesser
** General Public License version 2.1 as published by the Free Software
** Foundation and appearing in the file LICENSE.LGPL included in the
** packaging of this file.  Please review the following information to
** ensure the GNU Lesser General Public License version 2.1 requirements
** will be met: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html.
**
** In addition, as a special exception, Nokia gives you certain additional
** rights.  These rights are described in the Nokia Qt LGPL Exception
** version 1.1, included in the file LGPL_EXCEPTION.txt in this package.
**
** If you have questions regarding the use of this file, please contact
** Nokia at qt-info@nokia.com.
**
**
**
**
**
**
**
**
** $QT_END_LICENSE$
**
****************************************************************************/

#include "qgltexturemodel.h"

/*!
    \class QGLTextureModel
    \brief The QGLTextureModel class manages incremental texture geometry.
    \since 4.6
    \ingroup qt3d
    \ingroup qt3d::geometry

    The QGLTextureModel class encapsulates texture coordinates for the
    purpose of applying them to quad strips, extrusions and other
    iterated geometry generated by QGLDisplayList.

    The texture coordinates can be set on an individual basis for all four
    corners of the texture-mapping.  By default the coordinates are all
    invalid, and the specifier is null - that is isNull() returns true.

    In the simplest case the entire texture is applied to a quad:
    \code
    // origin 0, 0 and width x height of 1 x 1
    QGLTextureModel texSpec(0, 0, 1, 1);
    myDisplayList.appendQuad(a, b, c, d, texSpec);
    \endcode

    When a QGLTextureModel is applied to an extrusion or other iterated
    geometry, the QGLDisplayList calls startTileRight() and tileRight()
    to generate a sequence of texture coordinate sets, where the values of the
    coordinates are interpolated and tiled incrementally over
    the faces being textured.  These methods are advanced and are intended
    principally for internal use by the QGLDisplayList class.
*/

/*!
    Construct a null texture specifier.
*/
QGLTextureModel::QGLTextureModel()
    : m_bl(QLogicalVertex::InvalidTexCoord)
    , m_br(QLogicalVertex::InvalidTexCoord)
    , m_tr(QLogicalVertex::InvalidTexCoord)
    , m_tl(QLogicalVertex::InvalidTexCoord)
    , m_divisor(1.0f)
    , m_tile(0)
{
}

/*!
    Construct a rectangular QGLTextureModel with \a left and \a bottom origin
    coordinates, and the other coordinates determined by the \a width and \a height.
*/
QGLTextureModel::QGLTextureModel(qreal left, qreal bottom,
                                                qreal width, qreal height)
    : m_bl(left, bottom)
    , m_br(left + width, bottom)
    , m_tr(left + width, bottom + height)
    , m_tl(left, bottom + height)
    , m_divisor(1.0f)
    , m_tile(0)
{
}

/*!
    \fn QGLTextureModel::QGLTextureModel(const QGLTextureModel &other)
    Constructs a new texture model as a copy of \a other.
*/

/*!
    Delete this texture specifier, recovering any resources.
*/
QGLTextureModel::~QGLTextureModel()
{
    delete m_tile;
}

/*!
    \fn QGLTextureModel::operator=(const QGLTextureModel &other)
    Assigns this texture model to be a copy of \a other
*/

/*!
    \fn QVector2D QGLTextureModel::bottomLeft() const
    Returns the texture coordinate for the bottom left of this texture
    specifier.  Note that bottom is in the orientation as for OpenGL
    that is numerically lower values.
*/

/*!
    \fn void QGLTextureModel::setBottomLeft(const QVector2D &v)
    Sets the texture coordinate for the bottom left of this texture
    specifier to \a v.  Note that bottom is in the orientation as for OpenGL
    that is numerically lower values.
*/

/*!
    \fn QVector2D QGLTextureModel::bottomRight() const
    Returns the texture coordinate for the bottom left of this texture
    specifier.  Note that bottom is in the orientation as for OpenGL
    that is numerically lower values.
*/

/*!
    \fn void QGLTextureModel::setBottomRight(const QVector2D &v)
    Sets the texture coordinate for the bottom right of this texture
    specifier to \a v.  Note that bottom is in the orientation as for OpenGL
    that is numerically lower values.
*/

/*!
    \fn QVector2D QGLTextureModel::topLeft() const
    Returns the texture coordinate for the top left of this texture
    specifier.  Note that top is in the orientation as for OpenGL
    that is numerically higher values.
*/

/*!
    \fn QGLTextureModel::setTopLeft(const QVector2D &v)
    Sets the texture coordinate for the top left of this texture
    specifier to \a v.  Note that top is in the orientation as for OpenGL
    that is numerically higher values.
*/

/*!
    \fn QVector2D QGLTextureModel::topRight() const
    Returns the texture coordinate for the top right of this texture
    specifier.  Note that top is in the orientation as for OpenGL
    that is numerically higher values.
*/

/*!
    \fn void QGLTextureModel::setTopRight(const QVector2D &v)
    Sets the texture coordinate for the top right of this texture
    specifier to \a v.  Note that top is in the orientation as for OpenGL
    that is numerically higher values.
*/

/*!
    \fn bool QGLTextureModel::isNull() const
    Returns true if this texture specifier is null, that is all its corners
    are set to QLogicalVertex::InvalidTexCoord.
*/

/*!
    \fn void QGLTextureModel::startTileRight(qreal divisor)
    Reset this QGLTextureModel ready for a tiling of texture divisions.
    The coordinate values of this specifier will be divided over a coordinate
    distance specified by \a divisor.

    This is an advanced function intended principally for internal use
    by the QGLDisplayList class.

    \sa tileRight()
*/

/*!
    \fn QGLTextureModel QGLTextureModel::tileRight(qreal extent) const
    Returns a texture specifier for a tile \a extent wide.  The
    specifier returned will respectively have top-left and bottom-left
    equal to the top-right and bottom-right of the previously returned
    tiles; while the top-right and and bottom-right are advanced by the
    \a extent along an interpolated path from this specifiers corners.

    This is an advanced function intended principally for internal use
    by the QGLDisplayList class.

    \sa startTileRight()
*/
